# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: trusty
warnings_are_errors: true
sudo: false

matrix:
  include:
  - r: devel
  - r: release
    env: USE_VDIFFR=true
    r_github_packages:
    - lionel-/vdiffr

  - r: oldrel
  - r: 3.2
    env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - r: 3.1
    env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # switch off vdiffr by default
  - USE_VDIFFR=false

after_success:
  - Rscript -e 'covr::codecov()'