# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: trusty
warnings_are_errors: false
sudo: false

matrix:
  include:
  - r: oldrel 
  - r: release
  - r: release
    os: osx
    osx_image: xcode7.3
    before_install:
      - sudo tlmgr install framed titling
  - r: devel

  
