# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: trusty
warnings_are_errors: true
sudo: true

matrix:
  include:
  - r: devel
  - r: release
    env: 
      - USE_VDIFFR=true
      - R_CODECOV=true
    r_github_packages:
      - lionel-/vdiffr
  - r: oldrel

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # switch off vdiffr by default
  - USE_VDIFFR=false

after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev