# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: trusty
warnings_are_errors: true
sudo: false

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
  - r: 3.1
  - r: 3.2

